spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/DemoMailer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: byasebastien1991@gmail.com
    password: chwz wkgp jwtx ihvo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
logging:
  file:
    name: 'log.txt'
    path: '/'
  level:
    root: info


